name: "Nostradamus JS action"
description: "Nostradamus JS action"
author: "Jeroen Knoops <jeroen.knoops@philips.com>"
branding:
  color: orange

inputs:
  sourcePath:
    description: sourcePath
    required: true

outputs:
  newDependencies:
    description: New dependencies available?

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.sourcePath }}
